version: '3.7'
services:

  backend-mysql:
    container_name: backend-mysql
    image: mysql:latest
    restart: always
    ports:
      - "3307:3306"
    environment:
        MYSQL_DATABASE: translation_app
        MYSQL_USER: root
        MYSQL_PASSWORD: root
        MYSQL_ROOT_PASSWORD: root
    volumes:
      - .\docker\mysql\data:/var/lib/mysql
    networks:
      - backend





  backend-app:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - backend-mysql
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://backend-mysql:3306/translation_app?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
    networks:
      - backend

networks:
  backend:
    name: backend